// <auto-generated />
namespace Sistema.View.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MelhoradoPropertiesProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MelhoradoPropertiesProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271309402_Melhorado Properties Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
